### ISSUE TITLE
Hope to get your reply as soon as possible, thank you!

### ISSUE THREAD

**Issue by tianjiaowan** [yongsongH/AIDSRGAN-MICCAI2022#2]
Hello Mr. Huang, you have really done a great job.
But I have a problem while training, I hope to get your pointers.
File "/home/yg/PycharmProjects/pythonProject/AIDSRGAN-MICCAI2022-main/models/enhance_sr_denoising.py", line 199, in optimize_parameters
     self.G_delossfn_weight * self.G_lossfn(self.DE, self.LHR)#
RuntimeError: The size of tensor a (96) must match the size of tensor b (24) at non-singleton dimension 3
I don't know why the latitude does not match when calculating the loss function, I hope to get your reply as soon as possible, thank you very much

**Comment by yongsongH** [comment]
Hello! Thank you for your attention.
I would like to know if you have used our dataset?
Sometimes this problem occurs when the image channel counts are not compatible.

**Comment by tianjiaowan** [comment]
> Hello! Thank you for your attention. I would like to know if you have used our dataset? Sometimes this problem occurs when the image channel counts are not compatible.

Yes, I used your dataset and model and it still doesn't work
self.DE = self.netG(self.L)
self.G_delossfn_weight * self.G_lossfn(self.DE, self.LHR)
changed to
self.DE = self.netG(self.LHR)
self.G_delossfn_weight * self.G_lossfn(self.DE, self.H)
Do you think it is reasonable to do so

**Comment by yongsongH** [comment]
I'm sorry, I checked the code in my local environment, and it works well.
I don't recommend you made changes to the code, of course you can develop it according to your needs.
In addition, I still suggest you carefully check the datasets used.
As I mentioned in the README file, there will be unexpected errors if the upsampling factor is not correct.
If it still doesn't work, I have also released pre-trained models that can be used for reference.
Hope this is useful for you.

**Comment by tianjiaowan** [comment]
> I'm sorry, I checked the code in my local environment, and it works well. I don't recommend you made changes to the code, of course you can develop it according to your needs. In addition, I still suggest you carefully check the datasets used. As I mentioned in the README file, there will be unexpected errors if the upsampling factor is not correct. If it still doesn't work, I have also released pre-trained models that can be used for reference. Hope this is useful for you.


Ok, thanks for your answer and suggestion.
