### ISSUE TITLE
epochs and how many iterations

### ISSUE THREAD

**Issue by tianjiaowan** [yongsongH/AIDSRGAN-MICCAI2022#3]
Hello, senior Huang, how many epochs and how many iterations did you train in this work?

**Comment by yongsongH** [comment]
Hi, there 👋

I think the same question has been asked in another work, so I copied the answer:

In this work, there is no limit on the number of training epochs. However, GAN-based models have the risk of model collapse, I discourage a lot of training sessions. According to my experiments, the earlier experiments showed better results.
