### ISSUE TITLE
Question about training code

### ISSUE THREAD

**Issue by tianjiaowan** [yongsongH/AIDSRGAN-MICCAI2022#4]
Hello, Senior Huang, I'm sorry to ask you about the code again. I don't understand the following sentence very well:
  we propose a two-stage training approach to train the proposed AID-SRGAN, i.e., we first separately train the denoising module and SR module to obtain a relatively good denoising network and SR network, respectively. We then jointly train the denoising and SR modules in an end-to-end manner to further improve the performance.

I would like to ask what should I do at the beginning of training? To train a denoising model first, change the root to "denoising"? Or "superresolution", what else needs to be changed in the json file, and how to train a denoising model separately and super-resolution model? Could you please elaborate on how to train your code? Help us use it better, thanks
![2022-09-22 19-52-09屏幕截图](https://user-images.githubusercontent.com/105220722/191739688-ae663482-78c5-4133-99e7-82f7fee0dcf4.png)
![2022-09-22 19-51-35屏幕截图](https://user-images.githubusercontent.com/105220722/191739713-2076b138-9176-45dd-9afe-c5770e0001f0.png)

**Comment by yongsongH** [comment]
**Thank you for your attention.**

I will briefly respond to your concern.
In short, the method mentioned in the article can be achieved by simply changing the parameter settings.
For more details, please refer to the following table.


Parameter  |1st|2nd|3rd
---|:--:|---:|---:
G_srlossfn_weight|1e-5 | 0|1e-5 
G_delossfn_weight|0|1e-5 |1e-5 

We need three different training configurations, and before each new training we should import the pre-trained model from the previous phase.

**If our work is useful to you, welcome to cite it! Many thanks!** 🥳
