### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by yangzheng-yz** [yongsongH/AIDSRGAN-MICCAI2022#5]
Hi, Mr. Huang! Thanks for your great work!

I just read your paper and had some problems looking forward to your reply.
1. In your paper, it seems like that you constructed the input image from a HR image in a sequential scheme including adding noise-downsampling-compression. However, in your code, specifically in the [degradation_step1_nois.py], the preprocessing pipeline is not like the above Sequential style but like a random style. Does it mean that I do not need to do the sequential scheme to synthesize training input?
2. May I know whether the parameters for the blur part of degradation process are learnable? Or is it fixed before training and just used for generating training input images? 
Thanks for your time in advance.
Looking forward to your reply!

**Comment by yangzheng-yz** [comment]
Just have some sense about the introduction of attention mechanism: because the paper used random blur scheme for different images, for example the guassian blur would introduce like a global noise/influence when observing the image, but motion blur may introduce much more obvious noise/impact on the edge part than the background part. Therefore, the attention can be used to guide the CNN to denoise specific area. 

Is that understanding right?

Looking forward to your reply!

**Comment by yongsongH** [comment]
> Hi, Mr. Huang! Thanks for your great work!
> 
> I just read your paper and had some problems looking forward to your reply.
> 
> 1. In your paper, it seems like that you constructed the input image from a HR image in a sequential scheme including adding noise-downsampling-compression. However, in your code, specifically in the [degradation_step1_nois.py], the preprocessing pipeline is not like the above Sequential style but like a random style. Does it mean that I do not need to do the sequential scheme to synthesize training input?
> 2. May I know whether the parameters for the blur part of degradation process are learnable? Or is it fixed before training and just used for generating training input images?
>    Thanks for your time in advance.
>    Looking forward to your reply!

Hi, thank you for your attention to our work!
I will briefly reply to your concerns.

About the degradation pipeline, there are three different codes available for reference.
Please check the project.
I am not sure if I can get your point or not.

Using for generating training input images may be correct.

But I think in this work where we would like to propose the simulated degradation model close to reality.
And the SR model can learn from it to better represent the mapping between the two domains.

Hope this reply helps you.

**Comment by yongsongH** [comment]
> Just have some sense about the introduction of attention mechanism: because the paper used random blur scheme for different images, for example the guassian blur would introduce like a global noise/influence when observing the image, but motion blur may introduce much more obvious noise/impact on the edge part than the background part. Therefore, the attention can be used to guide the CNN to denoise specific area.
> 
> Is that understanding right?
> 
> Looking forward to your reply!

I think it should be a good idea to further explore.
Of course, the response to the different types of noise should be focused on the task.
The attention module used in this study would like to improve the denoising performance in the network.
To further confirm the specific domain, I think more ablation studies should be needed.
We will further focus on this point.
Thank you for pointing this out.

**Comment by yangzheng-yz** [comment]
> > Just have some sense about the introduction of attention mechanism: because the paper used random blur scheme for different images, for example the guassian blur would introduce like a global noise/influence when observing the image, but motion blur may introduce much more obvious noise/impact on the edge part than the background part. Therefore, the attention can be used to guide the CNN to denoise specific area.
> > Is that understanding right?
> > Looking forward to your reply!
> 
> I think it should be a good idea to further explore. Of course, the response to the different types of noise should be focused on the task. The attention module used in this study would like to improve the denoising performance in the network. To further confirm the specific domain, I think more ablation studies should be needed. We will further focus on this point. Thank you for pointing this out.

Thank you for your reply!
